trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: docker build -t $(docker_registry_addr)/$(image_name) .  # add options to this command to meet your needs
  displayName: 'Docker Build'

- script: |
    docker login -u $(docker_registry_user) -p $(docker_registry_passwd) $(docker_registry_addr)
    #docker push $(docker_registry_addr)/$(image_name)
    echo fuck
  displayName: 'Docker login'

- script: |
    docker push $(docker_registry_addr)/$(image_name)
    echo fuck
  displayName: 'Docker push'

